name: go-build

on:
  push:
    branches: [ "main" ]
    paths:
    - '!**.md'
    - '!**.yml'
    - '!**.tf'
  pull_request:
    branches: [ "main" ]
    paths:
    - '!**.md'
    - '!**.yml'
    - '!**.tf'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: stable

    - name: Build
      run: go build -v ./...
